### ISSUE TITLE
[LTB] Autoren und Lernenden Dashboards

### ISSUE THREAD

**Issue by FKneer** [e-Learning-by-SSE/nm-self-learning#141]
Implementierung der (Autoren- und Lernenden-)Dashboards und Navigation Seite. Grundlage sind die Konzepte aus e-learning-by-sse/nm-concept#25 und der Papierprototyp aus e-learning-by-sse/nm-concept#28.

Ziel ist die Überarbeitung des aktuellen Dashboards und die Integration der Learning Analytics und des Lerntagebuchs in die Plattform.  

UI:
- [ ] Übersicht/ Main page (Dashboard) #155 
- [ ] Seite für Einstellungen #154 
- [ ] Meine Kurse #156 
- [ ] Tagebuchübersicht (der Einträge) #169 
- [ ] Anzeige Eintrag #168
- [ ] Lernzielseite #164 

Integration:
- [ ] Lerntagebuch
- [ ] Learning Analytics

Status Sub-Tasks:
| Issues     | Mitarbeiter      | Status |
| ------------- | ------------- |------------- |
| #154   | @lukas-png   | Pull Request |
| #155  | @lukas-png  | Pull Request |
| #156  | @palfner-sse  | Pull Request |
| #164  | @FKneer ab 01.08. @Elscha   | Testing |
| #169  | @palfner-sse  |  Pull Request |
| #168  |  @palfner-sse | in Progress |
